### ISSUE TITLE
Bug in metering right side.

### ISSUE THREAD

**Issue by henrik1g** [sdenton4/pipic#12]
Thank you for providing this awesome piece of code! :-)

Found a bug in the metering right side.
Maybe consider (parts of) my patch.

Greets henrik

From 611b8fd7ae3908960212fa0ab76f3c89cea94cb5 Mon Sep 17 00:00:00 2001
From: Henrik Bieler Henrik.Bieler@nospam.de
Date: Wed, 5 Nov 2014 11:01:16 +0100
Subject: [PATCH 1/5] Fix bug in metering right side. Enable metering other
 than c. New meter modes bottom and top.

---

 timelapse.py | 23 +++++++++++++++++------
 1 file changed, 17 insertions(+), 6 deletions(-)

diff --git a/timelapse.py b/timelapse.py
index a9786f5..cb922ec 100644
--- a/timelapse.py
+++ b/timelapse.py
@@ -39,7 +39,7 @@ class timelapse:
         T=timelapse()
         T.listen()
     """
-    def **init**(self,w=1296,h=972,interval=15,maxtime=0,maxshots=0,targetBrightness=100,maxdelta=256):
-    def **init**(self,w=1296,h=972,interval=15,maxtime=0,maxshots=0,targetBrightness=70,maxdelta=256,metering='a'):
  
  ```
   self.w=w
   self.h=h
  ```
  
  @@ -51,7 +51,7 @@ class timelapse:
  
  ```
   #metersite is one of 'c', 'a', 'l', or 'r', for center, all, left or right.
   #Chooses a region of the image to use for brightness measurements.
  ```
-        self.metersite='c'
- ```
     self.metersite=metering
  
   f=open('/etc/hostname')
   hostname=f.read().strip().replace(' ','')
  ```
  
  @@ -84,6 +84,7 @@ class timelapse:
       print "\tinterval:\t", self.interval
       print "\tBrightns:\t", self.targetBrightness
       print "\tSize    :\t", self.w, 'x', self.h
- ```
     print "\tMetering:\t", self.metersite
  ```
  
   def **repr**(self):
       return 'A timelapse instance.'
  @@ -109,9 +110,19 @@ class timelapse:
           right=int(.3_w)+2
       elif meter=='r':
           top=int(1.0_h/2-.15*h)+1
-            bottom=int(1.0_w/2+.15_w)-1
-            left=h-int(.3*w)-2
-            bottom=int(1.0_h/2+.15_h)-1
-            left=w-int(.3*w)-2
           right=w
-        elif meter=='t':
-            top=0
-            bottom=int(.3*h)+2
-            left=int(1.0_w/2-.3_w)-1
-            right=int(1.0_w/2+.3_w)+1
-        elif meter=='b':
-            top=h-int(.3*h)-2
-            bottom=h
-            left=int(1.0_w/2-.3_w)-1
-            right=int(1.0_w/2+.3_w)+1
       else:
           top=0
           bottom=h
  @@ -320,11 +331,11 @@ def main(argv):
   parser.add_argument( '-n', '--maxshots', default=-1, type=int, help='Maximum number of photos to take.\nDefault is -1, for no maximum.' )
   parser.add_argument( '-b', '--brightness', default=128, type=int, help='Target average brightness of image, on a scale of 1 to 255.\nDefault is 128.' )
   parser.add_argument( '-d', '--delta', default=128, type=int, help='Maximum allowed distance of photo brightness from target brightness; discards photos too far from the target.  This is useful for autmatically discarding late-night shots.\nDefault is 128; Set to 256 to keep all images.' )
-    parser.add_argument( '-m', '--metering', default='a', type=str, choices=['a','c','l','r'], help='Where to average brightness for brightness calculations.\n"a" measures the whole image, "c" uses a window at the center, "l" meters a strip at the left, "r" uses a strip at the right.' )
-    parser.add_argument( '-m', '--metering', default='a', type=str, choices=['a','c','l','r','t','b'], help='Where to average brightness for brightness calculations.\n"a" measures the whole image, "c" uses a window at the center,\n"l" meters a strip at the left, "r" uses a strip at the right, "t" at top, "b" at bottom' )
   parser.add_argument( '-L', '--listen', action='store_true', help='Sets the timelapser to listen mode; listens for a master timelapser to tell it when to shoot.' )
  
   args=parser.parse_args()
-    TL = timelapse(w=args.width, h=args.height, interval=args.interval, maxshots=args.maxshots, maxtime=args.maxtime, targetBrightness=args.brightness, maxdelta=args.delta)
-    TL = timelapse(w=args.width, h=args.height, interval=args.interval, maxshots=args.maxshots, maxtime=args.maxtime, targetBrightness=args.brightness, maxdelta=args.delta, metering=args.metering)
  
   try:
  ##      os.listdir('/home/pi/pictures')
  
  1.9.1

**Comment by sdenton4** [comment]
Removed most of the metering code, and replaced it with better overall image metering.
