### ISSUE TITLE
Issues with  OmniVision OV5647 8mb camera

### ISSUE THREAD

**Issue by excalibur470** [sdenton4/pipic#16]
Hi @sdenton4,
I used your project obtaining very good results.
Now I bought the new  OmniVision OV5647 8mb camera and I am trying to use pipic but I am not able to get good photos.
The very first shot is pretty good (only a little dark) then a dozen of black images then a couple of clear images followed by other black ones.
I am using Raspberry Zero but I tested also PI 2 and PI 3 with the same results
Any ideas?

**Comment by sdenton4** [comment]
I'm afraid I haven't tried any newer hardware than the Pi2 with the standard (older) camera board.  If you find the issue, feel free to make a pull request.

**Comment by sdenton4** [comment]
This should be fixed by recent improvements to configurability of the script.
